package tc.srm620;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;


class c {
  char sl;
  int i;

  public c(char sl, int i) {
    this.sl = sl;
    this.i = i;
  }
}

public class CandidatesSelectionEasy {

  public int[] sort(String[] score, int x) {
    final List<c> cs = new ArrayList<c>();
    for (int i = 0; i < score.length; i++) {
      final char skillLevel = score[i].charAt(x);
      cs.add(new c(skillLevel, i));
    }

    Collections.sort(cs, new Comparator<c>() {
      @Override
      public int compare(c o1, c o2) {
        final int sl = o1.sl - o2.sl;
        if (sl == 0) {
          return o1.i - o2.i;
        }
        return sl;
      }
    });

    final int[] r = new int[score.length];
    for (int i = 0; i < score.length; i++) {
      r[i] = cs.get(i).i;
    }
    return r;
  }

  // BEGIN KAWIGIEDIT TESTING
  // Generated by KawigiEdit 2.1.4 (beta) modified by pivanof
  private static boolean KawigiEdit_RunTest(int testNum, String[] p0, int p1, boolean hasAnswer, int[] p2) {
    System.out.print("Test " + testNum + ": [" + "{");
    for (int i = 0; p0.length > i; ++i) {
      if (i > 0) {
        System.out.print(",");
      }
      System.out.print("\"" + p0[i] + "\"");
    }
    System.out.print("}" + "," + p1);
    System.out.println("]");
    CandidatesSelectionEasy obj;
    int[] answer;
    obj = new CandidatesSelectionEasy();
    final long startTime = System.currentTimeMillis();
    answer = obj.sort(p0, p1);
    final long endTime = System.currentTimeMillis();
    boolean res;
    res = true;
    System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
    if (hasAnswer) {
      System.out.println("Desired answer:");
      System.out.print("\t" + "{");
      for (int i = 0; p2.length > i; ++i) {
        if (i > 0) {
          System.out.print(",");
        }
        System.out.print(p2[i]);
      }
      System.out.println("}");
    }
    System.out.println("Your answer:");
    System.out.print("\t" + "{");
    for (int i = 0; answer.length > i; ++i) {
      if (i > 0) {
        System.out.print(",");
      }
      System.out.print(answer[i]);
    }
    System.out.println("}");
    if (hasAnswer) {
      if (answer.length != p2.length) {
        res = false;
      } else {
        for (int i = 0; answer.length > i; ++i) {
          if (answer[i] != p2[i]) {
            res = false;
          }
        }
      }
    }
    if (!res) {
      System.out.println("DOESN'T MATCH!!!!");
    } else if ((endTime - startTime) / 1000.0 >= 2) {
      System.out.println("FAIL the timeout");
      res = false;
    } else if (hasAnswer) {
      System.out.println("Match :-)");
    } else {
      System.out.println("OK, but is it right?");
    }
    System.out.println("");
    return res;
  }

  public static void main(String[] args) {
    boolean all_right;
    all_right = true;

    String[] p0;
    int p1;
    int[] p2;

    // ----- test 0 -----
    p0 = new String[]{"ACB", "BAC", "CBA"};
    p1 = 1;
    p2 = new int[]{1, 2, 0};
    all_right = KawigiEdit_RunTest(0, p0, p1, true, p2) && all_right;
    // ------------------

    // ----- test 1 -----
    p0 = new String[]{"A", "C", "B", "C", "A"};
    p1 = 0;
    p2 = new int[]{0, 4, 2, 1, 3};
    all_right = KawigiEdit_RunTest(1, p0, p1, true, p2) && all_right;
    // ------------------

    // ----- test 2 -----
    p0 = new String[]{"LAX", "BUR", "ONT", "LGB", "SAN", "SNA", "SFO", "OAK", "SJC"};
    p1 = 2;
    p2 = new int[]{5, 3, 8, 7, 4, 6, 1, 2, 0};
    all_right = KawigiEdit_RunTest(2, p0, p1, true, p2) && all_right;
    // ------------------

    // ----- test 3 -----
    p0 = new String[]{"BBCBABAC", "BCBACABA", "CCCBAACB", "CACABABB", "AABBBBCC"};
    p1 = 6;
    p2 = new int[]{0, 1, 3, 2, 4};
    all_right = KawigiEdit_RunTest(3, p0, p1, true, p2) && all_right;
    // ------------------

    // ----- test 4 -----
    p0 =
        new String[]{"XXYWZWWYXZ", "YZZZYWYZYW", "ZYZZWZYYWW", "ZWZWZWZXYW", "ZYXWZXWYXY", "YXXXZWXWXW", "XWWYZWXYXY", "XYYXYWYXWY", "ZZYXZYZXYY", "WXZXWYZWYY"};
    p1 = 3;
    p2 = new int[]{0, 3, 4, 5, 7, 8, 9, 6, 1, 2};
    all_right = KawigiEdit_RunTest(4, p0, p1, true, p2) && all_right;
    // ------------------

    // ----- test 5 -----
    p0 = new String[]{"X"};
    p1 = 0;
    p2 = new int[]{0};
    all_right = KawigiEdit_RunTest(5, p0, p1, true, p2) && all_right;
    // ------------------

    if (all_right) {
      System.out.println("You're a stud (at least on the example cases)!");
    } else {
      System.out.println("Some of the test cases had errors.");
    }
  }
  // END KAWIGIEDIT TESTING
}
// Powered by KawigiEdit 2.1.4 (beta) modified by pivanof!
