package tc.srm274;

import java.util.Arrays;

public class PalindromeMaker {
  public String make(String baseString) {
    char[] bs  = baseString.toCharArray();
    Arrays.sort(bs);

    int sz = bs.length;
    boolean foundMid = false;
    char[] palindrome = new char[bs.length];
    for (int i = 0, j = 0; i < sz;) {
      char c = bs[i];

      if (i == sz - 1 && foundMid == true) 
        return "";

      if (i == sz - 1 || c != bs[i+1]) {
        if (sz % 2 == 0 || foundMid == true)
          return "";
        else {
          foundMid = true;
          palindrome[sz/2] = c;
          i += 1;
        }
      } else {
        palindrome[j] = palindrome[sz - j - 1] = c;
        j += 1;
        i += 2;
      }
    }

    return new String(palindrome);
  }

  // BEGIN KAWIGIEDIT TESTING
  // Generated by KawigiEdit 2.1.4 (beta) modified by pivanof
  private static boolean KawigiEdit_RunTest(int testNum, String p0, boolean hasAnswer, String p1) {
    System.out.print("Test " + testNum + ": [" + "\"" + p0 + "\"");
    System.out.println("]");
    PalindromeMaker obj;
    String answer;
    obj = new PalindromeMaker();
    long startTime = System.currentTimeMillis();
    answer = obj.make(p0);
    long endTime = System.currentTimeMillis();
    boolean res;
    res = true;
    System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
    if (hasAnswer) {
      System.out.println("Desired answer:");
      System.out.println("\t" + "\"" + p1 + "\"");
    }
    System.out.println("Your answer:");
    System.out.println("\t" + "\"" + answer + "\"");
    if (hasAnswer) {
      res = answer.equals(p1);
    }
    if (!res) {
      System.out.println("DOESN'T MATCH!!!!");
    } else if ((endTime - startTime) / 1000.0 >= 2) {
      System.out.println("FAIL the timeout");
      res = false;
    } else if (hasAnswer) {
      System.out.println("Match :-)");
    } else {
      System.out.println("OK, but is it right?");
    }
    System.out.println("");
    return res;
  }
  public static void main(String[] args) {
    boolean all_right;
    all_right = true;

    String p0;
    String p1;

    // ----- test 0 -----
    p0 = "AABB";
    p1 = "ABBA";
    all_right = KawigiEdit_RunTest(0, p0, true, p1) && all_right;
    // ------------------

    // ----- test 1 -----
    p0 = "AAABB";
    p1 = "ABABA";
    all_right = KawigiEdit_RunTest(1, p0, true, p1) && all_right;
    // ------------------

    // ----- test 2 -----
    p0 = "ABACABA";
    p1 = "AABCBAA";
    all_right = KawigiEdit_RunTest(2, p0, true, p1) && all_right;
    // ------------------

    // ----- test 3 -----
    p0 = "ABCD";
    p1 = "";
    all_right = KawigiEdit_RunTest(3, p0, true, p1) && all_right;
    // ------------------

    if (all_right) {
      System.out.println("You're a stud (at least on the example cases)!");
    } else {
      System.out.println("Some of the test cases had errors.");
    }
  }
  // END KAWIGIEDIT TESTING
}
//Powered by KawigiEdit 2.1.4 (beta) modified by pivanof!
