package tc.srm393;

public class InstantRunoffVoting {
  boolean [] eliminated;
  String[] voters;
  int noOfCandidates;
  
  public int winner(String[] voters) {
    noOfCandidates = voters[0].length();
    
    this.voters = voters;
    eliminated = new boolean[noOfCandidates];
    
    for (int i = 0; i < noOfCandidates - 1; i++) {
      int winner = simulateRound();
      if (winner >= 0)
        return winner;
      if (winner == -2)
        return -1;
    }
    
    for (int i = 0; i < noOfCandidates; i++)
      if (eliminated[i] == false)
        return i;
    return -1;
  }

  private int simulateRound() {
    int [] votes = new int[noOfCandidates];
    
    for (int i = 0; i < voters.length; i++) {
      int j = 0;
      for (; j < voters[i].length() && 
             eliminated[Character.digit(voters[i].charAt(j), 10)] == true; j++) 
        ;
      if (j == voters[i].length())
        return -2;
      votes[Character.digit(voters[i].charAt(j), 10)] += 1;
    }
    
    for (int i = 0; i < votes.length; i++)
      if (votes[i]/(double)voters.length * 100 > 50)
        return i;
    
    int min = Integer.MAX_VALUE;
    for (int i = 0; i < noOfCandidates; i++)
      if (votes[i] < min && eliminated[i] == false)
        min = votes[i];

    for (int i = 0; i < noOfCandidates; i++)
      if (votes[i] == min)
        eliminated[i] = true;
    
    return -1;
  }

  // BEGIN KAWIGIEDIT TESTING
  // Generated by KawigiEdit 2.1.4 (beta) modified by pivanof
  private static boolean KawigiEdit_RunTest(int testNum, String[] p0, boolean hasAnswer, int p1) {
    System.out.print("Test " + testNum + ": [" + "{");
    for (int i = 0; p0.length > i; ++i) {
      if (i > 0) {
        System.out.print(",");
      }
      System.out.print("\"" + p0[i] + "\"");
    }
    System.out.print("}");
    System.out.println("]");
    InstantRunoffVoting obj;
    int answer;
    obj = new InstantRunoffVoting();
    long startTime = System.currentTimeMillis();
    answer = obj.winner(p0);
    long endTime = System.currentTimeMillis();
    boolean res;
    res = true;
    System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
    if (hasAnswer) {
      System.out.println("Desired answer:");
      System.out.println("\t" + p1);
    }
    System.out.println("Your answer:");
    System.out.println("\t" + answer);
    if (hasAnswer) {
      res = answer == p1;
    }
    if (!res) {
      System.out.println("DOESN'T MATCH!!!!");
    } else if ((endTime - startTime) / 1000.0 >= 2) {
      System.out.println("FAIL the timeout");
      res = false;
    } else if (hasAnswer) {
      System.out.println("Match :-)");
    } else {
      System.out.println("OK, but is it right?");
    }
    System.out.println("");
    return res;
  }
  public static void main(String[] args) {
    boolean all_right;
    all_right = true;

    String[] p0;
    int p1;

    // ----- test 0 -----
    p0 = new String[]{"01","10","01","01","10"};
    p1 = 0;
    all_right = KawigiEdit_RunTest(0, p0, true, p1) && all_right;
    // ------------------

    // ----- test 1 -----
    p0 = new String[]{"120","102","210","021","012"};
    p1 = 1;
    all_right = KawigiEdit_RunTest(1, p0, true, p1) && all_right;
    // ------------------

    // ----- test 2 -----
    p0 = new String[]{"10","01"};
    p1 = -1;
    all_right = KawigiEdit_RunTest(2, p0, true, p1) && all_right;
    // ------------------

    // ----- test 3 -----
    p0 = new String[]{"3120","3012","1032","3120","2031","2103","1230","1230"};
    p1 = -1;
    all_right = KawigiEdit_RunTest(3, p0, true, p1) && all_right;
    // ------------------

    // ----- test 4 -----
    p0 = new String[]{"24103","30412","32014","21043","30412","32401","14203","04123","30241","02413","13042","01432","01342","32401","24301","12430","41023","02413","42310","12043"};
    p1 = 1;
    all_right = KawigiEdit_RunTest(4, p0, true, p1) && all_right;
    // ------------------

    // ----- test 5 -----
    p0 = new String[]{"0649853172","2146875039","2671548309","5897216403","4719823056","7945213860","9021538647","9286145307","9176403528","3709486152"};
    p1 = 9;
    all_right = KawigiEdit_RunTest(5, p0, true, p1) && all_right;
    // ------------------

    if (all_right) {
      System.out.println("You're a stud (at least on the example cases)!");
    } else {
      System.out.println("Some of the test cases had errors.");
    }
  }
  // END KAWIGIEDIT TESTING
}
//Powered by KawigiEdit 2.1.4 (beta) modified by pivanof!
