package tc.misc.dp;

public class PalindromistTest {

  // BEGIN KAWIGIEDIT TESTING
  // Generated by KawigiEdit 2.1.4 (beta) modified by pivanof
  private static boolean KawigiEdit_RunTest(int testNum, String p0, String[] p1, boolean hasAnswer, String p2) {
    System.out.print("Test " + testNum + ": [" + "\"" + p0 + "\"" + "," + "{");
    for (int i = 0; p1.length > i; ++i) {
      if (i > 0) {
        System.out.print(",");
      }
      System.out.print("\"" + p1[i] + "\"");
    }
    System.out.print("}");
    System.out.println("]");
    Palindromist obj;
    String answer;
    obj = new Palindromist();
    long startTime = System.currentTimeMillis();
    answer = obj.palindrome(p0, p1);
    long endTime = System.currentTimeMillis();
    boolean res;
    res = true;
    System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
    if (hasAnswer) {
      System.out.println("Desired answer:");
      System.out.println("\t" + "\"" + p2 + "\"");
    }
    System.out.println("Your answer:");
    System.out.println("\t" + "\"" + answer + "\"");
    if (hasAnswer) {
      res = answer.equals(p2);
    }
    if (!res) {
      System.out.println("DOESN'T MATCH!!!!");
    } else if ((endTime - startTime) / 1000.0 >= 2) {
      System.out.println("FAIL the timeout");
      res = false;
    } else if (hasAnswer) {
      System.out.println("Match :-)");
    } else {
      System.out.println("OK, but is it right?");
    }
    System.out.println("");
    return res;
  }
  
  public static void main(String[] args) {
    boolean all_right;
    all_right = true;

    String p0;
    String[] p1;
    String p2;

    // ----- test 0 -----
    p0 = "AMANAPLANAC";
    p1 = new String[]{"A","CANAL","MAN","PANAMA","PLAN"};
    p2 = "A MAN A PLAN A CANAL PANAMA";
    all_right = KawigiEdit_RunTest(0, p0, p1, true, p2) && all_right;
    // ------------------

    // ----- test 1 -----
    p0 = "AAAAA";
    p1 = new String[]{"AA","A","AAA"};
    p2 = "A A A A A A A A A";
    all_right = KawigiEdit_RunTest(1, p0, p1, true, p2) && all_right;
    // ------------------

    // ----- test 2 -----
    p0 = "CBA";
    p1 = new String[]{"CBABC","CBAABC"};
    p2 = "CBAABC";
    all_right = KawigiEdit_RunTest(2, p0, p1, true, p2) && all_right;
    // ------------------

    // ----- test 3 -----
    p0 = "RACEFAST";
    p1 = new String[]{"AR","CAR","FAST","RACE","SAFE","CEFA","ACE","STTS","AFEC"};
    p2 = "RACE FAST SAFE CAR";
    all_right = KawigiEdit_RunTest(3, p0, p1, true, p2) && all_right;
    // ------------------

    // ----- test 4 -----
    p0 = "AABAABA";
    p1 = new String[]{"AA","AAB","BAA","BAB"};
    p2 = "AA BAA BAA BAA BAA";
    all_right = KawigiEdit_RunTest(4, p0, p1, true, p2) && all_right;
    // ------------------

    // ----- test 5 -----
    p0 = "STRAWNOTOOSTUPIDAF";
    p1 = new String[]{"WARTS","I","TOO","A","FAD","STUPID","STRAW","PUT","NO","ON","SOOT"};
    p2 = "STRAW NO TOO STUPID A FAD I PUT SOOT ON WARTS";
    all_right = KawigiEdit_RunTest(5, p0, p1, true, p2) && all_right;
    // ------------------

    // ----- test 6 -----
    p0 = "AAAAA";
    p1 = new String[]{"AAAA"};
    p2 = "";
    all_right = KawigiEdit_RunTest(6, p0, p1, true, p2) && all_right;
    // ------------------

    // ----- test 7 -----
    p0 = "A";
    p1 = new String[]{"A","AA"};
    p2 = "A";
    all_right = KawigiEdit_RunTest(7, p0, p1, true, p2) && all_right;
    // ------------------

    if (all_right) {
      System.out.println("You're a stud (at least on the example cases)!");
    } else {
      System.out.println("Some of the test cases had errors.");
    }
  }
  // END KAWIGIEDIT TESTING
}
