package tc.srm480;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.HashSet;
import java.util.List;
import java.util.Set;


public class InternetSecurity {
  public String[] determineWebsite(String[] address, String[] keyword, String[] dangerous, int threshold) {
    boolean[] safe = new boolean[address.length];
    Arrays.fill(safe, true);
    Set<String> dangerousKeywords = new HashSet<String>(Arrays.asList(dangerous));

    int i = 0;
    while (i < address.length) {
      Collection<String> keywords = Arrays.asList(keyword[i].split(" "));
      if (safe[i] && count(dangerousKeywords, keywords) >= threshold) {
        safe[i] = false;
        dangerousKeywords.addAll(keywords);
        i = 0;
        continue;
      }
      i += 1;
    }

    List<String> result = new ArrayList<String>();
    for (i = 0; i < address.length; i++) {
      if (!safe[i]) {
        result.add(address[i]);
      }
    }
    return result.toArray(new String[0]);
  }

  private int count(Set<String> dangerousKeywords, Collection<String> keywords) {
    int count = 0;
    for (String k : keywords) {
      if (dangerousKeywords.contains(k)) {
        count += 1;
      }
    }
    return count;
  }

  // BEGIN KAWIGIEDIT TESTING
  // Generated by KawigiEdit 2.1.4 (beta) modified by pivanof
  private static boolean KawigiEdit_RunTest(int testNum, String[] p0, String[] p1, String[] p2, int p3,
      boolean hasAnswer, String[] p4) {
    System.out.print("Test " + testNum + ": [" + "{");
    for (int i = 0; p0.length > i; ++i) {
      if (i > 0) {
        System.out.print(",");
      }
      System.out.print("\"" + p0[i] + "\"");
    }
    System.out.print("}" + "," + "{");
    for (int i = 0; p1.length > i; ++i) {
      if (i > 0) {
        System.out.print(",");
      }
      System.out.print("\"" + p1[i] + "\"");
    }
    System.out.print("}" + "," + "{");
    for (int i = 0; p2.length > i; ++i) {
      if (i > 0) {
        System.out.print(",");
      }
      System.out.print("\"" + p2[i] + "\"");
    }
    System.out.print("}" + "," + p3);
    System.out.println("]");
    InternetSecurity obj;
    String[] answer;
    obj = new InternetSecurity();
    long startTime = System.currentTimeMillis();
    answer = obj.determineWebsite(p0, p1, p2, p3);
    long endTime = System.currentTimeMillis();
    boolean res;
    res = true;
    System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
    if (hasAnswer) {
      System.out.println("Desired answer:");
      System.out.print("\t" + "{");
      for (int i = 0; p4.length > i; ++i) {
        if (i > 0) {
          System.out.print(",");
        }
        System.out.print("\"" + p4[i] + "\"");
      }
      System.out.println("}");
    }
    System.out.println("Your answer:");
    System.out.print("\t" + "{");
    for (int i = 0; answer.length > i; ++i) {
      if (i > 0) {
        System.out.print(",");
      }
      System.out.print("\"" + answer[i] + "\"");
    }
    System.out.println("}");
    if (hasAnswer) {
      if (answer.length != p4.length) {
        res = false;
      } else {
        for (int i = 0; answer.length > i; ++i) {
          if (!answer[i].equals(p4[i])) {
            res = false;
          }
        }
      }
    }
    if (!res) {
      System.out.println("DOESN'T MATCH!!!!");
    } else if ((endTime - startTime) / 1000.0 >= 2) {
      System.out.println("FAIL the timeout");
      res = false;
    } else if (hasAnswer) {
      System.out.println("Match :-)");
    } else {
      System.out.println("OK, but is it right?");
    }
    System.out.println("");
    return res;
  }

  public static void main(String[] args) {
    boolean all_right;
    all_right = true;

    String[] p0;
    String[] p1;
    String[] p2;
    int p3;
    String[] p4;

    // ----- test 0 -----
    p0 = new String[]{"www.topcoder.com", "www.sindicate_of_evil.com", "www.happy_citizens.com"};
    p1 =
        new String[]{"hack encryption decryption internet algorithm", "signal interference evil snake poison algorithm", "flower baloon topcoder blue sky sea"};
    p2 = new String[]{"hack", "encryption", "decryption", "interference", "signal", "internet"};
    p3 = 3;
    p4 = new String[]{"www.topcoder.com", "www.sindicate_of_evil.com"};
    all_right = KawigiEdit_RunTest(0, p0, p1, p2, p3, true, p4) && all_right;
    // ------------------

    // ----- test 1 -----
    p0 = new String[]{"brokenlink", "flowerpower.net", "purchasedomain.com"};
    p1 = new String[]{"broken", "rose tulips", "cheap free domain biggest greatest"};
    p2 = new String[]{"biggest", "enemy", "hideout"};
    p3 = 2;
    p4 = new String[]{};
    all_right = KawigiEdit_RunTest(1, p0, p1, p2, p3, true, p4) && all_right;
    // ------------------

    // ----- test 2 -----
    p0 = new String[]{"a..a.ab.", "...aa.b"};
    p1 = new String[]{"a bc def", "def ghij klmno"};
    p2 = new String[]{"a", "b", "c", "d", "e"};
    p3 = 1;
    p4 = new String[]{"a..a.ab.", "...aa.b"};
    all_right = KawigiEdit_RunTest(2, p0, p1, p2, p3, true, p4) && all_right;
    // ------------------

    // ----- test 3 -----
    p0 = new String[]{"www.tsa.gov"};
    p1 = new String[]{"information assurance signal intelligence research"};
    p2 = new String[]{"signal", "assurance", "penguin"};
    p3 = 2;
    p4 = new String[]{"www.tsa.gov"};
    all_right = KawigiEdit_RunTest(3, p0, p1, p2, p3, true, p4) && all_right;
    // ------------------

    if (all_right) {
      System.out.println("You're a stud (at least on the example cases)!");
    } else {
      System.out.println("Some of the test cases had errors.");
    }
  }
  // END KAWIGIEDIT TESTING
}
//Powered by KawigiEdit 2.1.4 (beta) modified by pivanof!
