package tc.misc;

import java.util.*;
import java.util.regex.*;
import java.text.*;
import java.math.*;


public class AverageAverage
{
	boolean[] used;
	int L;
	double Gavg;
	int[] list;
	
	public double average(int[] numList) {
		list = numList;
		used = new boolean[numList.length];
		L = numList.length;//System.out.println(L);
		perm(0);//System.out.println(".."+Gavg);
		return Gavg/(Math.pow(2, L) - 1);
	}
	
	void perm(int len){
		if(len == L){
			int sum=0, cnt=0;
			for(int i=0; i<L;i++){
				sum += used[i] ? list[i] : 0;
				cnt += used[i] ? 1 : 0;
			}
			double avg = cnt ==0 ? 0 : ((double)sum)/cnt;
			Gavg += avg;//System.out.println( ";;;;" +Gavg);
			return;
		}
		
		used[len] = true;
		perm(len+1);
		used[len] = false;
		perm(len+1);
	}
	
	
	
	
	
	// BEGIN KAWIGIEDIT TESTING
	// Generated by KawigiEdit 2.1.4 (beta) modified by pivanof
	private static boolean KawigiEdit_RunTest(int testNum, int[] p0, boolean hasAnswer, double p1) {
		System.out.print("Test " + testNum + ": [" + "{");
		for (int i = 0; p0.length > i; ++i) {
			if (i > 0) {
				System.out.print(",");
			}
			System.out.print(p0[i]);
		}
		System.out.print("}");
		System.out.println("]");
		AverageAverage obj;
		double answer;
		obj = new AverageAverage();
		long startTime = System.currentTimeMillis();
		answer = obj.average(p0);
		long endTime = System.currentTimeMillis();
		boolean res;
		res = true;
		System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
		if (hasAnswer) {
			System.out.println("Desired answer:");
			System.out.println("\t" + p1);
		}
		System.out.println("Your answer:");
		System.out.println("\t" + answer);
		if (hasAnswer) {
			res = Math.abs(p1 - answer) <= 1e-9 * Math.max(1.0, Math.abs(p1));
		}
		if (!res) {
			System.out.println("DOESN'T MATCH!!!!");
		} else if ((endTime - startTime) / 1000.0 >= 2) {
			System.out.println("FAIL the timeout");
			res = false;
		} else if (hasAnswer) {
			System.out.println("Match :-)");
		} else {
			System.out.println("OK, but is it right?");
		}
		System.out.println("");
		return res;
	}
	public static void main(String[] args) {
		boolean all_right;
		all_right = true;
		
		int[] p0;
		double p1;
		
		// ----- test 0 -----
		p0 = new int[]{1,2,3};
		p1 = 2.0D;
		all_right = KawigiEdit_RunTest(0, p0, true, p1) && all_right;
		// ------------------
		
		// ----- test 1 -----
		p0 = new int[]{42};
		p1 = 42.0D;
		all_right = KawigiEdit_RunTest(1, p0, true, p1) && all_right;
		// ------------------
		
		// ----- test 2 -----
		p0 = new int[]{3,1,4,15,9};
		p1 = 6.4D;
		all_right = KawigiEdit_RunTest(2, p0, true, p1) && all_right;
		// ------------------
		
		if (all_right) {
			System.out.println("You're a stud (at least on the example cases)!");
		} else {
			System.out.println("Some of the test cases had errors.");
		}
	}
	// END KAWIGIEDIT TESTING
}
//Powered by KawigiEdit 2.1.4 (beta) modified by pivanof!
