package tc.misc;

public class MicrowaveSelling {
  public int mostAttractivePrice(int minPrice, int maxPrice) {
    int maxNines = -1;
    int n = -1;

    for (int p = maxPrice; p >= minPrice; p--) {
      int nines = countNines(p);
      if (nines > maxNines) {
        n = p;
        maxNines = nines;
      }
    }
    return n;
  }

  private int countNines(int p) {
    int nines = 0;
    while (p != 0) {
      int digit = p % 10;
      if (digit == 9) {
        nines++;
      } else {
        break;
      }
      p /= 10;
    }
    return nines;
  }

  // BEGIN KAWIGIEDIT TESTING
  // Generated by KawigiEdit 2.1.4 (beta) modified by pivanof
  private static boolean KawigiEdit_RunTest(int testNum, int p0, int p1, boolean hasAnswer, int p2) {
    System.out.print("Test " + testNum + ": [" + p0 + "," + p1);
    System.out.println("]");
    MicrowaveSelling obj;
    int answer;
    obj = new MicrowaveSelling();
    long startTime = System.currentTimeMillis();
    answer = obj.mostAttractivePrice(p0, p1);
    long endTime = System.currentTimeMillis();
    boolean res;
    res = true;
    System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
    if (hasAnswer) {
      System.out.println("Desired answer:");
      System.out.println("\t" + p2);
    }
    System.out.println("Your answer:");
    System.out.println("\t" + answer);
    if (hasAnswer) {
      res = answer == p2;
    }
    if (!res) {
      System.out.println("DOESN'T MATCH!!!!");
    } else if ((endTime - startTime) / 1000.0 >= 2) {
      System.out.println("FAIL the timeout");
      res = false;
    } else if (hasAnswer) {
      System.out.println("Match :-)");
    } else {
      System.out.println("OK, but is it right?");
    }
    System.out.println("");
    return res;
  }

  public static void main(String[] args) {
    boolean all_right;
    all_right = true;

    int p0;
    int p1;
    int p2;

    // ----- test 0 -----
    p0 = 460;
    p1 = 680;
    p2 = 599;
    all_right = KawigiEdit_RunTest(0, p0, p1, true, p2) && all_right;
    // ------------------

    // ----- test 1 -----
    p0 = 10;
    p1 = 1000;
    p2 = 999;
    all_right = KawigiEdit_RunTest(1, p0, p1, true, p2) && all_right;
    // ------------------

    // ----- test 2 -----
    p0 = 1255;
    p1 = 2999;
    p2 = 2999;
    all_right = KawigiEdit_RunTest(2, p0, p1, true, p2) && all_right;
    // ------------------

    // ----- test 3 -----
    p0 = 20;
    p1 = 25;
    p2 = 25;
    all_right = KawigiEdit_RunTest(3, p0, p1, true, p2) && all_right;
    // ------------------

    if (all_right) {
      System.out.println("You're a stud (at least on the example cases)!");
    } else {
      System.out.println("Some of the test cases had errors.");
    }
  }
  // END KAWIGIEDIT TESTING
}
//Powered by KawigiEdit 2.1.4 (beta) modified by pivanof!
