package topcoder.misc.dp;

public class MoneyExchangeTest {
  //BEGIN KAWIGIEDIT TESTING
  // Generated by KawigiEdit 2.1.4 (beta) modified by pivanof
  private static boolean KawigiEdit_RunTest(int testNum, String[] p0, String p1, String p2, boolean hasAnswer,
      double p3) {
    System.out.print("Test " + testNum + ": [" + "{");
    for (int i = 0; p0.length > i; ++i) {
      if (i > 0) {
        System.out.print(",");
      }
      System.out.print("\"" + p0[i] + "\"");
    }
    System.out.print("}" + "," + "\"" + p1 + "\"" + "," + "\"" + p2 + "\"");
    System.out.println("]");
    MoneyExchange obj;
    double answer;
    obj = new MoneyExchange();
    long startTime = System.currentTimeMillis();
    answer = obj.bestRate(p0, p1, p2);
    long endTime = System.currentTimeMillis();
    boolean res;
    res = true;
    System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
    if (hasAnswer) {
      System.out.println("Desired answer:");
      System.out.println("\t" + p3);
    }
    System.out.println("Your answer:");
    System.out.println("\t" + answer);
    if (hasAnswer) {
      res = Math.abs(p3 - answer) <= 1e-9 * Math.max(1.0, Math.abs(p3));
    }
    if (!res) {
      System.out.println("DOESN'T MATCH!!!!");
    } else if ((endTime - startTime) / 1000.0 >= 2) {
      System.out.println("FAIL the timeout");
      res = false;
    } else if (hasAnswer) {
      System.out.println("Match :-)");
    } else {
      System.out.println("OK, but is it right?");
    }
    System.out.println("");
    return res;
  }

  public static void main(String[] args) {
    boolean all_right;
    all_right = true;

    String[] p0;
    String p1;
    String p2;
    double p3;

    // ----- test 0 -----
    p0 = new String[]{"A 1 B 10", "B 1 C 3", "C 1 B 4", "A 4 D 8", "D 7 E 4"};
    p1 = "A";
    p2 = "E";
    p3 = 1.1428571428571428D;
    all_right = KawigiEdit_RunTest(0, p0, p1, p2, true, p3) && all_right;
    // ------------------

    // ----- test 1 -----
    p0 = new String[]{"EUR 0008 USD 0010"};
    p1 = "USD";
    p2 = "EUR";
    p3 = -1.0D;
    all_right = KawigiEdit_RunTest(1, p0, p1, p2, true, p3) && all_right;
    // ------------------

    // ----- test 2 -----
    p0 = new String[]{"EUR 8 USD 10", "EUR 1 GOODBUY 2", "GOODBUY 1 USD 2"};
    p1 = "EUR";
    p2 = "USD";
    p3 = 4.0D;
    all_right = KawigiEdit_RunTest(2, p0, p1, p2, true, p3) && all_right;
    // ------------------

    // ----- test 3 -----
    p0 = new String[]{"A 1 B 2", "A 1 C 3", "B 2 D 3", "C 9 D 10", "D 7 E 2"};
    p1 = "A";
    p2 = "E";
    p3 = 0.9523809523809523D;
    all_right = KawigiEdit_RunTest(3, p0, p1, p2, true, p3) && all_right;
    // ------------------

    // ----- test 4 -----
    p0 = new String[]{};
    p1 = "TYPEA";
    p2 = "TYPEB";
    p3 = -1.0D;
    all_right = KawigiEdit_RunTest(4, p0, p1, p2, true, p3) && all_right;
    // ------------------

    // ----- test 5 -----
    p0 = new String[]{"A 7 A 5", "A 1 B 1", "B 2 A 2"};
    p1 = "A";
    p2 = "A";
    p3 = 1.0D;
    all_right = KawigiEdit_RunTest(5, p0, p1, p2, true, p3) && all_right;
    // ------------------

    if (all_right) {
      System.out.println("You're a stud (at least on the example cases)!");
    } else {
      System.out.println("Some of the test cases had errors.");
    }
  }
  // END KAWIGIEDIT TESTING
}
