import java.util.Arrays;
import java.util.Comparator;

public class ContestSchedule {
  Comparator<String> comparator = new Comparator<String>() {
    @Override
    public int compare(String o1, String o2) {
      if (startTime(o1) <= startTime(o2))
        return -1;
      if (startTime(o1) > startTime(o2))
        return 1;
      return 0;
    }
  };

  public double expectedWinnings(String[] contests) {
    Arrays.sort(contests, comparator);

    final int[] s = new int[contests.length];
    s[0] = percent(contests[0]);

    for (int i = 1; i < contests.length; i++) {
      s[i] = percent(contests[i]);
      for (int j = i - 1; j >= 0; j--) {
        if (!overlaps(contests[i], contests[j]) && s[j] + percent(contests[i]) > s[i]) {
          s[i] = s[j] + percent(contests[i]);
        }
      }
    }

    int max = -1;
    for (int i = 0; i < contests.length; i++)
      if (s[i] > max)
        max = s[i];

    return max / 100.0;
  }

  private boolean overlaps(String a, String b) {
    if (startTime(a) > startTime(b))
      return overlaps(b, a);
    return startTime(b) < endTime(a);
  }

  private int startTime(String contest) {
    return Integer.parseInt(contest.split(" ")[0]);
  }

  private int endTime(String contest) {
    return Integer.parseInt(contest.split(" ")[1]);
  }

  private int percent(String contest) {
    return Integer.parseInt(contest.split(" ")[2]);
  }

  // BEGIN KAWIGIEDIT TESTING
  // Generated by KawigiEdit 2.1.4 (beta) modified by pivanof
  private static boolean KawigiEdit_RunTest(int testNum, String[] p0, boolean hasAnswer, double p1) {
    System.out.print("Test " + testNum + ": [" + "{");
    for (int i = 0; p0.length > i; ++i) {
      if (i > 0) {
        System.out.print(",");
      }
      System.out.print("\"" + p0[i] + "\"");
    }
    System.out.print("}");
    System.out.println("]");
    ContestSchedule obj;
    double answer;
    obj = new ContestSchedule();
    final long startTime = System.currentTimeMillis();
    answer = obj.expectedWinnings(p0);
    final long endTime = System.currentTimeMillis();
    boolean res;
    res = true;
    System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
    if (hasAnswer) {
      System.out.println("Desired answer:");
      System.out.println("\t" + p1);
    }
    System.out.println("Your answer:");
    System.out.println("\t" + answer);
    if (hasAnswer) {
      res = Math.abs(p1 - answer) <= 1e-9 * Math.max(1.0, Math.abs(p1));
    }
    if (!res) {
      System.out.println("DOESN'T MATCH!!!!");
    } else if ((endTime - startTime) / 1000.0 >= 2) {
      System.out.println("FAIL the timeout");
      res = false;
    } else if (hasAnswer) {
      System.out.println("Match :-)");
    } else {
      System.out.println("OK, but is it right?");
    }
    System.out.println("");
    return res;
  }

  public static void main(String[] args) {
    boolean all_right;
    all_right = true;

    String[] p0;
    double p1;

    // ----- test 0 -----
    p0 = new String[] { "1 10 100", "10 20 100", "20 30 100", "30 40 100" };
    p1 = 4.0D;
    all_right = KawigiEdit_RunTest(0, p0, true, p1) && all_right;
    // ------------------

    // ----- test 1 -----
    p0 = new String[] { "10 20 20", "30 40 60", "15 35 90" };
    p1 = 0.9D;
    all_right = KawigiEdit_RunTest(1, p0, true, p1) && all_right;
    // ------------------

    // ----- test 2 -----
    p0 = new String[] { "1 100 85", "99 102 100", "101 200 60" };
    p1 = 1.45D;
    all_right = KawigiEdit_RunTest(2, p0, true, p1) && all_right;
    // ------------------

    // ----- test 3 -----
    p0 = new String[] { "1 1000000000 1" };
    p1 = 0.01D;
    all_right = KawigiEdit_RunTest(3, p0, true, p1) && all_right;
    // ------------------

    // ----- test 4 -----
    p0 =
        new String[] {
            "1361955 8940967 10",
            "628145516 644285978 17",
            "883515280 910484865 36",
            "762888635 769291174 52",
            "98152102 136328674 1",
            "9580638 20450682 50",
            "646139319 664648341 20",
            "484027666 505290970 57",
            "841082555 879295329 99",
            "940563715 966953344 4",
            "579113528 595261527 25",
            "925801172 962952912 9",
            "285845005 307916055 45",
            "403573723 410697485 10",
            "9467290 25698952 90",
            "631265400 650639733 3",
            "520690249 559261759 96",
            "491747709 531061081 86",
            "643215695 672420161 94",
            "614608448 617341712 44",
            "456517316 491770747 24",
            "806956091 828414045 88",
            "528156706 559510719 15",
            "158398859 190439269 4",
            "743974602 761975244 49",
            "882264704 887725893 1",
            "877444309 884479317 59",
            "785986538 806192822 19",
            "732553407 747696021 81",
            "132099860 148305810 97",
            "555144412 572785730 99",
            "506507263 535927950 82",
            "489726669 505160939 90",
            "793692316 804153358 99",
            "901329638 919179990 10",
            "29523791 44318662 58",
            "570497239 595701008 73",
            "706091347 730328348 23",
            "118054686 135301010 39",
            "307178252 337804001 93",
            "896162463 900667971" +
                " 39",
            "271356542 273095245 80",
            "865692962 891795950 91",
            "593986003 596160000 58",
            "807688147 831190344 59",
            "468916697 496462595 92" };
    p1 = 14.12D;
    all_right = KawigiEdit_RunTest(4, p0, true, p1) && all_right;
    // ------------------

    if (all_right) {
      System.out.println("You're a stud (at least on the example cases)!");
    } else {
      System.out.println("Some of the test cases had errors.");
    }
  }
  // END KAWIGIEDIT TESTING
}
// Powered by KawigiEdit 2.1.4 (beta) modified by pivanof!
